### PR TITLE
Add freeglut3-dev for openGL dependances

### PR DESCRIPTION
**Pull request by Boyquotes**

### CODE REVIEW

**Comment by auriamg** [comment]
Can you explain why? STK does not use GLUT

**Comment by Boyquotes** [comment]
Because OpenGL was not found during 'cmake ..' command and the freeglut package provide them

On Debian 8

See Cmakeoutput.log
[CMakeOutput.txt](https://github.com/supertuxkart/stk-editor/files/292879/CMakeOutput.txt)

**Comment by Boyquotes** [comment]
The log don't contain the error...

root@debian:/home/nico/stk-editor/build# cmake ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- No build type selected, default to Release
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.0/Modules/FindOpenGL.cmake:175 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:37 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/nico/stk-editor/build/CMakeFiles/CMakeOutput.log".

**Comment by deveee** [comment]
Did you mean libgl1-mesa-dev and mesa-common-dev?

**Comment by Boyquotes** [comment]
Yes, only add : libgl1-mesa-dev and mesa-common-dev for build stk-editor on debian 8

I close this pull request and make another with a new line
"
On debian 8
apt-get install ...  libgl1-mesa-dev  mesa-common-dev ...
"

Or just add this 2 package at the current line like this pull request libgl1-mesa-dev mesa-common-dev
?

**Comment by deveee** [comment]
You don't need to write "On debian 8" because this command should be valid
for most Debian based distributions.

I would just add these packages at the single line. Ideally if the line has
more than 80 characters, it could be something like this:

```
apt-get install package1 package2 \
package3 package4 etc...
```

But it looks that nobody cares here about this, so you can do what you
prefer ;)

**Pull request closed without merging**
